// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/_layout.tsx";
import * as $3 from "./routes/_middleware.tsx";
import * as $4 from "./routes/api/file/[name].ts";
import * as $5 from "./routes/api/init.ts";
import * as $6 from "./routes/api/logout.ts";
import * as $7 from "./routes/api/note/[note].ts";
import * as $8 from "./routes/api/note/index.ts";
import * as $9 from "./routes/api/note/list.ts";
import * as $10 from "./routes/api/search/[note]/[column].ts";
import * as $11 from "./routes/api/sheet/[note]/[uuid].ts";
import * as $12 from "./routes/api/sheet/[note]/index.ts";
import * as $13 from "./routes/api/signin.ts";
import * as $14 from "./routes/api/signup.ts";
import * as $15 from "./routes/api/storage/[uuid].ts";
import * as $16 from "./routes/api/storage/upload.ts";
import * as $17 from "./routes/index.ts";
import * as $18 from "./routes/note/[note].tsx";
import * as $19 from "./routes/note/create.tsx";
import * as $20 from "./routes/note/index.tsx";
import * as $21 from "./routes/signin.tsx";
import * as $22 from "./routes/signup.tsx";
import * as $$0 from "./islands/ColumnList.tsx";
import * as $$1 from "./islands/ColumnOptions.tsx";
import * as $$2 from "./islands/CreateColumnList.tsx";
import * as $$3 from "./islands/CreateColumnOptions.tsx";
import * as $$4 from "./islands/CreateNoteButton.tsx";
import * as $$5 from "./islands/CreateNoteForm.tsx";
import * as $$6 from "./islands/DeleteNote.tsx";
import * as $$7 from "./islands/NavEnd.tsx";
import * as $$8 from "./islands/NoteBlock.tsx";
import * as $$9 from "./islands/RuleList.tsx";
import * as $$10 from "./islands/RuleOptions.tsx";
import * as $$11 from "./islands/SignInForm.tsx";
import * as $$12 from "./islands/SignUpForm.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/_layout.tsx": $2,
    "./routes/_middleware.tsx": $3,
    "./routes/api/file/[name].ts": $4,
    "./routes/api/init.ts": $5,
    "./routes/api/logout.ts": $6,
    "./routes/api/note/[note].ts": $7,
    "./routes/api/note/index.ts": $8,
    "./routes/api/note/list.ts": $9,
    "./routes/api/search/[note]/[column].ts": $10,
    "./routes/api/sheet/[note]/[uuid].ts": $11,
    "./routes/api/sheet/[note]/index.ts": $12,
    "./routes/api/signin.ts": $13,
    "./routes/api/signup.ts": $14,
    "./routes/api/storage/[uuid].ts": $15,
    "./routes/api/storage/upload.ts": $16,
    "./routes/index.ts": $17,
    "./routes/note/[note].tsx": $18,
    "./routes/note/create.tsx": $19,
    "./routes/note/index.tsx": $20,
    "./routes/signin.tsx": $21,
    "./routes/signup.tsx": $22,
  },
  islands: {
    "./islands/ColumnList.tsx": $$0,
    "./islands/ColumnOptions.tsx": $$1,
    "./islands/CreateColumnList.tsx": $$2,
    "./islands/CreateColumnOptions.tsx": $$3,
    "./islands/CreateNoteButton.tsx": $$4,
    "./islands/CreateNoteForm.tsx": $$5,
    "./islands/DeleteNote.tsx": $$6,
    "./islands/NavEnd.tsx": $$7,
    "./islands/NoteBlock.tsx": $$8,
    "./islands/RuleList.tsx": $$9,
    "./islands/RuleOptions.tsx": $$10,
    "./islands/SignInForm.tsx": $$11,
    "./islands/SignUpForm.tsx": $$12,
  },
  baseUrl: import.meta.url,
};

export default manifest;
