// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/_middleware.tsx";
import * as $3 from "./routes/api/file/[name].ts";
import * as $4 from "./routes/api/init.ts";
import * as $5 from "./routes/api/logout.ts";
import * as $6 from "./routes/api/note/[note].ts";
import * as $7 from "./routes/api/note/index.ts";
import * as $8 from "./routes/api/note/list.ts";
import * as $9 from "./routes/api/search/[note]/[column].ts";
import * as $10 from "./routes/api/sheet/[note]/[uuid].ts";
import * as $11 from "./routes/api/sheet/[note]/index.ts";
import * as $12 from "./routes/api/signin.ts";
import * as $13 from "./routes/api/signup.ts";
import * as $14 from "./routes/api/storage/[uuid].ts";
import * as $15 from "./routes/api/storage/upload.ts";
import * as $16 from "./routes/greet/[name].tsx";
import * as $17 from "./routes/index.tsx";
import * as $$0 from "./islands/Counter.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/_middleware.tsx": $2,
    "./routes/api/file/[name].ts": $3,
    "./routes/api/init.ts": $4,
    "./routes/api/logout.ts": $5,
    "./routes/api/note/[note].ts": $6,
    "./routes/api/note/index.ts": $7,
    "./routes/api/note/list.ts": $8,
    "./routes/api/search/[note]/[column].ts": $9,
    "./routes/api/sheet/[note]/[uuid].ts": $10,
    "./routes/api/sheet/[note]/index.ts": $11,
    "./routes/api/signin.ts": $12,
    "./routes/api/signup.ts": $13,
    "./routes/api/storage/[uuid].ts": $14,
    "./routes/api/storage/upload.ts": $15,
    "./routes/greet/[name].tsx": $16,
    "./routes/index.tsx": $17,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
